version: '3'
services:
  database:
    image: postgres:12.1
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /tmp:/tmp
    ports:
      - 5432:5432
    env_file:
      - .database_dev.env
    expose:
      - 5432
  backend:
    image: node:14.15.4
    expose:
      - 3000
    working_dir: /app
    command: bash -c "npm install && npm run start:dev"
    env_file:
      - .backend.env
    depends_on:
      - database
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/app
  web:
    image: node:14.15.4
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    env_file:
      - .web.env
    ports:
      - 8080:8080
    depends_on: 
      - backend
    volumes:
      - ./web:/app
volumes:
  postgres-data:
      driver: local